name: sheet
version: 1.0.0
homepage: https://github.com/SunnatilloShavkatov/sheet
description: 'A fully customizable draggable bottom sheet.'

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  analysis_lints: ^1.0.1

flutter:
  uses-material-design: true
