name: sheet
description: A fully customizable draggable bottom sheet.
version: 1.0.0
homepage: https://github.com/SunnatilloShavkatov/sheet

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  meta: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  lints: ^5.0.0

flutter:

  uses-material-design: true
